### ISSUE TITLE
Visible item not marked as visible on Chrome

### ISSUE THREAD

**Issue by johansmitsnl** [Synphonyte/leptos-use#20] opened 2023-08-07 16:54 UTC
When you are tracking visibility of a item that is visible on page load it is not marked visible. Only when you scroll away and back again to mark it visible.

In Firefox it works but Chrome it does not.

**Comment by maccesch** [comment] 2023-08-07 19:50
Just to be sure: You're talking about [use_element_visibility](https://leptos-use.rs/elements/use_element_visibility.html), right? The docs demo seems to work for me, both in Firefox and Chrome. 

Can you provide some code to reproduce?

**Comment by johansmitsnl** [comment] 2023-08-07 21:11
Indeed element visibility. And I can confirm that the examples work but not in my case. 
Perhaps it is because of the suspense. I'll try to make a small app to replicate the issue.

**Comment by johansmitsnl** [comment] 2023-08-10 17:54
I have made a [example](https://github.com/johansmitsnl/leptos-test/tree/chrome-element-visibility) and also a [video](https://github.com/Synphonyte/leptos-use/assets/12995632/0ed16814-b84e-45ba-9696-415706f85a9f). It looks like a raise as you can see that on multiple reload retries it fails sometimes.

**Comment by maccesch** [comment] 2023-08-10 20:41
So turns out that Chrome in some circumstances likes to send an errorneous intersection observer entry. It is now filtered out.

Fixed in 2a27141

**Closed by maccesch** 2023-08-10 20:41 UTC
