### ISSUE TITLE
use_timestamp spams these two warnings when I add it to my project.

### ISSUE THREAD

**Issue by sjud** [Synphonyte/leptos-use#52] opened 2023-11-14 20:58 UTC
I've added use_timestamp to a component and didn't make use of the signal.
I get these two errors spammed into my console (very fast, like request animation frame speed) in Firefox.
```rust
At /Users/sam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-use-0.8.2/src/use_timestamp.rs:87:25, you access a signal or memo (defined at /Users/sam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-use-0.8.2/src/use_timestamp.rs:76:24) outside a reactive tracking context. This might mean your app is not responding to changes in signal values in the way you expect.

Here’s how to fix it:

1. If this is inside a `view!` macro, make sure you are passing a function, not a value.
  ❌ NO  <p>{x.get() * 2}</p>
  ✅ YES <p>{move || x.get() * 2}</p>

2. If it’s in the body of a component, try wrapping this access in a closure: 
  ❌ NO  let y = x.get() * 2
  ✅ YES let y = move || x.get() * 2.

3. If you’re *trying* to access the value without tracking, use `.get_untracked()` or `.with_untracked()` instead. [site_os.js:626:9](http://0.0.0.0:8080/pkg/site_os.js)
At /Users/sam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-use-0.8.2/src/use_raf_fn.rs:92:27, you access a signal or memo (defined at /Users/sam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-use-0.8.2/src/use_raf_fn.rs:55:35) outside a reactive tracking context. This might mean your app is not responding to changes in signal values in the way you expect.

Here’s how to fix it:

1. If this is inside a `view!` macro, make sure you are passing a function, not a value.
  ❌ NO  <p>{x.get() * 2}</p>
  ✅ YES <p>{move || x.get() * 2}</p>

2. If it’s in the body of a component, try wrapping this access in a closure: 
  ❌ NO  let y = x.get() * 2
  ✅ YES let y = move || x.get() * 2.

3. If you’re *trying* to access the value without tracking, use `.get_untracked()` or `.with_untracked()` instead.
```
Thanks for your time.

**Comment by maccesch** [comment] 2023-11-15 21:13
Thanks for reporting this. Will look at it ASAP. It's actually a duplicate of #45 .

Will close in favor of that other issue.

**Closed by maccesch** 2023-11-15 21:13 UTC
