### ISSUE TITLE
weird behavior of `use_cookie`

### ISSUE THREAD

**Issue by sify21** [Synphonyte/leptos-use#95] opened 2024-03-21 14:09 UTC
I created a sample project here for demonstrating: https://github.com/sify21/leptos-actix-middleware

Pay attention to `CookiePage1`,`CookiePage2`, `cookie1`, `cookie2` and related signals/effects.

After the server is up, proceed with following steps:
1. Open the browser and developer tools, go to `http://localhost:3000/cookie1`
  In server logs, you would see a log `cookie1 not set, setting to set-by-server`; in browser console logs, you would see a log `cookie1 not set, setting to set-by-browser`; and in browser, cookie1's real value would be `set-by-browser`. 

This is the first mis-behavior, I expect that the html response of `/cookie1` from the server should set the response header  `Set-Cookie`, so cookie1's value should be `set-by-server`. During hydration in browser, the printed log should be `cookie1 is set, current value set-by-server` .

2. Remember the `Expires/Max-Age` value of cookie1 in the browser. Set the string value of `first` and `second` text input to be the same, then hit `Validate` button.
  You would be redirected to page `/cookie2`, you would also notice that the `Expires/Max-Age` value of `cookie1` is updated. In browser's console, a log would be printed: `Effects: cookie2 is changed to Some("Same")`

Step 2 contains three mis-behaviors:
- Why cookie1's `Expires/Max-Age` is updated?
- If cookie1 is updated for whatever reason, since `Expires/Max-Age` is different,  then effects that depend on cookie1's signal should run, and a log should be printed in browser's console: `Effects: cookie1 is changed to {some-value}`
- although cookie2's effect runs, cookie2's value is actually not stored in browser's cookie storage 

Actually I'm not sure if this is a bug in `use_cookie`. I'm just a beginner with leptos framework, so maybe it's a misuse in my own code but I just couldn't find out.

**Comment by sify21** [comment] 2024-03-22 10:00
> Just learned that `Cookie` is a property of `Document`. So maybe I should `use_cookie` exactly in the `#[component]` where I would update them? Currently this is what I'm doing: `use_cookie` in `App`, store the returned signals in the global context, and then update cookie in another `#[component]` using the write-signal retrieved from the global context. Because I thought that would avoid the overhead of calling `use_cookie` multiple times.

I added another page `LocalCookiePage1` for comparison, the only difference is how the `WriteSignal` of `cookie2` is retrieved. 

Here is the result:
- In `CookiePage1`, no matter how many times you hit the `Validate` button, `cookie2` won't be set.
- In `LocalCookiePage1`, the first time you hit the button, behavior is the same as `CookiePage1`. But if you navigate back to `LocalCookiePage1` and validate again, `cookie2` is set correctly.

This is an improvement, but why it doesn't work the first time?

**Comment by sify21** [comment] 2024-03-22 13:41
I studied the code of `use_cookie`,  what it actually does is converting events from a named `BroadcastChannel` to a  leptos signal called `message`,  and `message signal` has an effect that modifies another leptos signal called `cookie`, and `cookie signal` has a pausable watch that writes the document's cookie as well as  post an event  to the `BroadcastChannel`.

When `message signal`'s effect is running, `cookie signal`'s pausable watch is paused.

So the situation of `cookie2`'s not being set correctly must be related to that paused watch.

**Comment by maccesch** [comment] 2024-04-02 09:59
1. Initial value of cookie1

This is actually expected behavior because you don't provide a default value for the cookie. So if the cookie is not set yet there will be no `Set-Cookie` header for it. After that you set the value to `set-by-browser` which then get's send to the server in subsequent calls.

2. Cookie2

All of this has been fixed by #96 

Thanks for reporting this and sorry it took so long!

**Closed by maccesch** 2024-04-02 09:59 UTC
